const data = {
  products: [
    {
      _id: '1',
      name: 'REPOSTO - Trainers',
      category: 'Sport',
      image: [
        '/images/product-1-1.jpg',
        '/images/product-1-2.webp',
        '/images/product-1-3.webp',
        '/images/product-1-4.webp',
        '/images/product-1-5.webp',
        '/images/product-1-6.webp',
      ],
      price: 79,
      brand: 'Nike',
      brand_logo: '/images/nike-logo.webp',
      color: 'black',
      rating: 4.5,
      numReviews: 10,
      countInStock: [
        { size: 36, qty: 0 },
        { size: 37, qty: 1 },
        { size: 38, qty: 1 },
        { size: 39, qty: 3 },
        { size: 40, qty: 1 },
        { size: 42, qty: 0 },
        { size: 44, qty: 5 },
        { size: 45, qty: 3 },
      ],
      adding_date: '2022/01/02',
    },
    {
      _id: '2',
      name: 'CROCOS - Trainers',
      category: 'Sport',
      image: ['/images/product-2.jpg'],
      price: 117,
      brand: 'Lacoste',
      brand_logo: '/images/lacoste-logo.jpg',
      color: 'black',
      rating: 4.2,
      numReviews: 3345,
      countInStock: [
        { size: 39, qty: 3 },
        { size: 40, qty: 1 },
        { size: 42, qty: 0 },
        { size: 43, qty: 3 },
        { size: 44, qty: 5 },
      ],
      adding_date: '2021/12/02',
    },
    {
      _id: '3',
      name: 'XT-WINGS 2 UNISEX - Trainers',
      category: 'Sport',
      image: ['/images/product-3.jpg'],
      price: 129,
      brand: 'Salomon',
      brand_logo: '/images/salomon-logo.svg',
      color: 'black',
      rating: 5.0,
      numReviews: 2345,
      countInStock: [
        { size: 39, qty: 3 },
        { size: 40, qty: 1 },
        { size: 42, qty: 0 },
        { size: 43, qty: 3 },
        { size: 44, qty: 5 },
      ],
      adding_date: '2021/11/02',
    },
    {
      _id: '4',
      name: 'MULTIX UNISEX - Trainers',
      category: 'Sport',
      image: ['/images/product-4.jpg'],
      price: 89,
      brand: 'adidas',
      brand_logo: '/images/adidas-logo.png',
      color: 'gray',
      rating: 3.5,
      numReviews: 345,
      countInStock: [
        { size: 39, qty: 3 },
        { size: 40, qty: 1 },
        { size: 42, qty: 0 },
        { size: 43, qty: 3 },
        { size: 44, qty: 5 },
      ],
      adding_date: '2021/10/02',
    },
    {
      _id: '5',
      name: 'NUCLEUS - Trainers',
      category: 'Sport',
      image: ['/images/product-5.jpg'],
      price: 40,
      brand: 'Puma',
      brand_logo: '/images/puma-logo.jpg',
      color: 'white',
      rating: 2.5,
      numReviews: 35,
      countInStock: [
        { size: 39, qty: 3 },
        { size: 40, qty: 1 },
        { size: 42, qty: 0 },
        { size: 43, qty: 3 },
        { size: 44, qty: 5 },
      ],
      adding_date: '2021/09/02',
    },
    {
      _id: '6',
      name: 'SUPER DELUX - Trainers',
      category: 'Sport',
      image: ['/images/product-6.jpg'],
      price: 149,
      brand: 'EA7 Emporio Armani',
      brand_logo: '/images/emporio-armani-logo.png',
      color: 'black',
      rating: 1.5,
      numReviews: 6665,
      countInStock: [
        { size: 39, qty: 3 },
        { size: 40, qty: 1 },
        { size: 42, qty: 0 },
        { size: 43, qty: 3 },
        { size: 44, qty: 5 },
      ],
      adding_date: '2022/02/02',
    },
  ],
};

export default data;
